# Generated by Django 5.1.1 on 2024-09-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='project',
            field=models.CharField(choices=[('bulba', 'BULBA'), ('flamingo', 'FLAMINGO'), ('constellation', 'CONSTELLATION')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='grt_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
