# Generated by Django 5.1.1 on 2024-10-01 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_usertask_project_alter_usertask_grt_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='leadtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grt_id1', models.CharField(max_length=100, unique=True)),
                ('team_lead1', models.CharField(max_length=255)),
                ('name1', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='usertask',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usertask',
            name='team_lead',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='grt_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.leadtask'),
        ),
    ]
