# Generated by Django 5.1.1 on 2024-10-01 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_leadtask_usertask_name_usertask_team_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='grt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.leadtask'),
        ),
    ]
